[package]
name = "superlu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
superlu-sys = { git = "https://github.com/HenrikJStromberg/superlu-sys.git", branch = "master" }
libc = "0.2.151"
matrix = "0.22.0"
sprs = "0.11"
ndarray = "0.15.6"
